# Site settings
title: "Johannes Konings"
email: mail@johanneskonings.dev
description: "personal site and some articles"
baseurl: ""
url: "https://johanneskonings.dev"
title_description: ""
title_image: "./img/avartar.png"
google_analytics: "UA-168757907-1"
github_repository: https://github.com/JohannesKonings/JohannesKonings.github.io
post_limit: 5

# Social usernames/URLs
email_address: mail@johanneskonings.dev
twitter_username: KoningsJohannes
github_username:  JohannesKonings
dev-to_username: JohannesKonings
linkedin_link: https://www.linkedin.com/in/johanneskonings
stackoverflow_link: https://stackoverflow.com/users/13017141/johannes-konings
xing_link: https://www.xing.com/profile/Johannes_Konings/

# Footer
footer_left: "<a href=\"/impressum.html\">Impressum</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/JohannesKonings/JohannesKonings.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
