packages:
  # all packages in direct subdirs of packages/
  - "websites/*"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.8
  vitest: npm:@voidzero-dev/vite-plus-test@latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
