/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as BlogIndexRouteImport } from "./routes/blog/index";
import { Route as BlogPostIdRouteImport } from "./routes/blog/$postId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: "/blog/",
  path: "/blog/",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: "/blog/$postId",
  path: "/blog/$postId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/blog/$postId": typeof BlogPostIdRoute;
  "/blog": typeof BlogIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/blog/$postId": typeof BlogPostIdRoute;
  "/blog": typeof BlogIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/blog/$postId": typeof BlogPostIdRoute;
  "/blog/": typeof BlogIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/blog/$postId" | "/blog";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/blog/$postId" | "/blog";
  id: "__root__" | "/" | "/blog/$postId" | "/blog/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BlogPostIdRoute: typeof BlogPostIdRoute;
  BlogIndexRoute: typeof BlogIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/": {
      id: "/blog/";
      path: "/blog";
      fullPath: "/blog";
      preLoaderRoute: typeof BlogIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/$postId": {
      id: "/blog/$postId";
      path: "/blog/$postId";
      fullPath: "/blog/$postId";
      preLoaderRoute: typeof BlogPostIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogPostIdRoute: BlogPostIdRoute,
  BlogIndexRoute: BlogIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
