name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run format check
        run: pnpm run format:check

      - name: Run lint check
        run: pnpm run lint:check
        continue-on-error: true

      - name: Run astro build
        run: pnpm run build:astro
